wandb_settings:
  exp_name: encoder_training
  exp_dir: "" # Add full path of experiments folder
  project: clap
  group: encoder
  dryrun: False
data_params:
  name: maze2d # NOTE: door, relocate, pen, hammer
  include_section_ids_in_tokenizer: True
  data_seed: 1337
  k: 5
  size: medium # umaze, hard, expert, human
  filter_start: False
  filter_end: False
model_params: 
  encoder: cl
  latent_dim: 8
  n_layers: 2
  eps: 1e-6
  hidden_size: 128
  mlp: False
  language_encoder: GPT2 
  filepath: null
  pretrained_name: null
loss_params:
  loss: brownian_bridge
  name: simclr
optim_params: 
  batch_size: 32
  decay_steps: 5e4
  decay_factor: 0.1
  learning_rate: 0.0001
  moving_average_decay: 0.9999
  momentum: 0.9
experiment_params:
  validate: True
  checkpoint_epochs: 10
  continue_from_checkpoint: True
  num_epochs: 100
  cuda: True
  seed: 1337
  data_loader_workers: 8
